version: 1
disable_existing_loggers: yes

formatters:
  standard:
    class: coloredlogs.ColoredFormatter
    format: "%(asctime)s [%(levelname)8s] : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  standard_detailed:
    format: "%(asctime)s|%(levelname)8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  error:
    format: "%(asctime)s [%(levelname)8s] %(name)s.%(funcName)s() : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  error_detailed:
    format: "%(asctime)s|%(name)s|%(levelname)8s|<PID %(process)d:%(processName)s>|%(name)s.%(funcName)s| %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  debug:
    format: "%(asctime)s [%(levelname)8s] %(name)s.%(funcName)s(%(lineno)s) : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  debug_detailed:
    format: "%(asctime)s|%(name)s|%(levelname)s|<PID %(process)d:%(processName)s>|%(name)s.%(funcName)s(%(lineno)s)|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard_detailed
    filename: mediainfo-generator.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard_detailed
    filename: mediainfo-generator.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error_detailed
    filename: mediainfo-generator.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: debug_detailed
    filename: mediainfo-generator.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  info_console_handler:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  warn_console_handler:
    class: logging.StreamHandler
    level: WARN
    formatter: standard
    stream: ext://sys.stdout

  error_console_handler:
    class: logging.StreamHandler
    level: ERROR
    formatter: error
    stream: ext://sys.stderr

  debug_console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: debug
    stream: ext://sys.stdout

root:
    level: NOTSET
    handlers: [info_console_handler]
    propogate: no

loggers:
  # root:
  #   handlers: [info_console_handler, error_console_handler]
  #   propagate: no
  mediainfo_generator:
    handlers: [info_console_handler]
    level: INFO
    propagate: no
